cStoreMVC.UI/cStoreMVC.UI/Controllers/AuthorsADOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using cStoreMVC.DATA.ADO;
using cStoreMVC.DOMAIN.Models;

namespace cStoreMVC.UI.Controllers
{
    public class AuthorsADOController : Controller
    {
        //Createa an instance of the Data Access Layer (class)
        AuthorsDAL authors = new AuthorsDAL();

        // GET: AuthorsADO
        public ActionResult Index()
        {
            //Return all author first names using DAL method
            ViewBag.FirstNames = authors.GetFirstNames();
            return View();
        }
        public ActionResult GetAuthors()
        {
            //
            return View(authors.GetAuthors());
        }//GetAuthors()

        //NEEDS GET AND POST, Creates an empty form for the end user to add an Author
        public ActionResult CreateAuthor()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult CreateAuthor(AuthorModel author)
        {
            if (ModelState.IsValid)//ServerSideValidation
            {
                //Call to our AuthorsDAL object to use the 
                //CreateAuthor() which will create an author
                //with the values passed from the view
                authors.CreateAuthor(author);
                return RedirectToAction("GetAuthors");
            }//if ModelState.IsValid

            //If the end user entered BAD author info, send them back to the 
            //CreateAuthor view with the info that was entered and show validation errors on the client

            return View(author);
        }

        public ActionResult AuthorDetails(int id)
        {
            //Create an author object and populate it's values using the FindAuthor() to display on the view
            AuthorModel author = authors.FindAuthor(id);
            return View(author);
        }

        public ActionResult UpdateAuthor(int id)
        {
            //Return the author object AND populate the form
            return View(authors.FindAuthor(id));
        }//updateAuthor()
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateAuthor(AuthorModel author)
        {
            if (ModelState.IsValid)
            {
                authors.UpdateAuthor(author);
                //Send the end user back to the list of authors
                return RedirectToAction("GetAuthors");
            }
            return View(author);
        }
        public ActionResult DeleteAuthor (int id)
        {
            authors.DeleteAuthor(id);
            return RedirectToAction("GetAuthors");
        }//DeleteAuthor

        public ActionResult LinqExamples()
        {
            /*
             * LINQ (Language INtegrated Query) is a technology used to interact with data objects.
             * There are 2 different syntax that we use with LINQ
             * 
             * Method Syntax - uses objects and C# methods to interact with data
             * 
             * Query Syntax - C# Keywords written in SQL execution order
             */
            #region NY State Authors
            //Get all authors from NY state

            //Method Syntax
            //var nyAuthors = authors.GetAuthors().Where(a => a.State == "NY");

            //Query Syntax 
            var nyAuthors = (from a in authors.GetAuthors() where a.State == "NY" select a).OrderBy(a => a.LastName);
            //return View(nyAuthors);
            #endregion
            #region ViewBag Property Example
            var firstNames = (from a in authors.GetAuthors() select a.FirstName).ToList();

            ViewBag.LinqFirstNames = firstNames;
            return View();
            #endregion
        }//LinqExamples()
    }//end class
}//end namespace

cStoreMVC.UI/cStoreMVC.UI/Controllers/PublishersADOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using cStoreMVC.DATA.ADO;
using cStoreMVC.DOMAIN.Models;

namespace cStoreMVC.UI.Controllers
{
    public class PublishersADOController : Controller
    {
        //Createa an instance of the Data Access Layer (class)
        PublishersDAL publishers = new PublishersDAL();

        // GET: PublishersADO
        public ActionResult Index()
        {
            //Return all publisher first names using DAL method
            ViewBag.PublisherNames = publishers.GetPublisherNames();
            return View();
        }

        public ActionResult GetPublishers()
        {
            return View(publishers.GetPublishers());
        }//GetPublishers()

        //NEEDS GET AND POST, Creates an empty form for the end user to add an Publisher
        public ActionResult CreatePublisher()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult CreatePublisher(PublisherModel Publisher)
        {
            if (ModelState.IsValid)//ServerSideValidation
            {
                //Call to our PublishersDAL object to use the 
                //CreatePublisher() which will create an Publisher
                //with the values passed from the view
                publishers.CreatePublisher(Publisher);
                return RedirectToAction("GetPublishers");
            }//if ModelState.IsValid

            //If the end user entered BAD Publisher info, send them back to the 
            //CreatePublisher view with the info that was entered and show validation errors on the client

            return View(Publisher);
        }
        public ActionResult PublisherDetails(int id)
        {
            //Create an publisher object and populate it's values using the FindPublisher() to display on the view
            PublisherModel publisher = publishers.FindPublisher(id);
            return View(publisher);
        }

        public ActionResult UpdatePublisher(int id)
        {
            //Return the publisher object AND populate the form
            return View(publishers.FindPublisher(id));
        }//updatePublisher()
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdatePublisher(PublisherModel publisher)
        {
            if (ModelState.IsValid)
            {
                publishers.UpdatePublisher(publisher);
                //Send the end user back to the list of publishers
                return RedirectToAction("GetPublishers");
            }
            return View(publisher);
        }

        public ActionResult DeletePublisher(int id)
        {
            publishers.DeletePublisher(id);
            return RedirectToAction("GetPublishers");
        }//DeletePublisher


    }//end class
}//end namespace

cStoreMVC.UI/cStoreMVC.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title | cStore</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0/jquery-ui.min.css" rel="stylesheet" />
    <link href="https://code.jquery.com/ui/1.12.0/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
    <link href="~/Content/Styles/main.css" rel="stylesheet">
    <link href="~/Content/Styles/responsive.css" rel="stylesheet">

    <link rel="shortcut icon" href="Content/Images/Ico/favicon.ico">
</head><!--/head-->
<body>
    <header id="header">
        <!--header-->
        <div class="header_top">
            <!--header_top-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="contactinfo">
                            <ul class="nav nav-pills">
                                <li><a href="tel:+01-913-322-7000"><i class="fa fa-phone"></i> 913-322-7000</a></li>
                                <li><a href="mailto:info@centriqcstore.com"><i class="fa fa-envelope"></i> info@centriqcstore.com</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="social-icons pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href="https://www.facebook.com/CentriqTraining/" target="_blank"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="https://twitter.com/CentriqTraining" target="_blank"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="https://www.linkedin.com/company/centriq-foss-training" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="https://www.youtube.com/user/CentriqTraining" target="_blank"><i class="fa fa-youtube"></i></a></li>
                                <li><a href="#https://plus.google.com/108553092060324883743" target="_blank"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header_top-->

        <div class="header-middle">
            <!--header-middle-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="logo pull-left">
                            <a href="~/"><span>Centriq</span> cStore</a>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="shop-menu pull-right">
                            <ul class="nav navbar-nav">
                                <!-- Unauthenticated -->
                                <li id="cart-button">
                                    <a href="#"><i class="fa fa-shopping-cart"></i> Cart</a>
                                    <span id="cart-notification" class="notification-counter"></span>
                                </li>
                                <li><a href="#"><i class="fa fa-user"></i> Register</a></li>
                                <li><a href="#"><i class="fa fa-lock"></i> Login</a></li>
                                <!-- Authenticated -->
                                <!--
                                <li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li>
                                <li><a href="#"><i class="fa fa-shopping-cart"></i> Cart</a></li>
                                <li><a href="#"><i class="fa fa-user"></i> Account</a></li>
                                <li><a href="#"><i class="fa fa-lock"></i> Logout</a></li>
                                -->
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-middle-->

        <div class="header-bottom">
            <!--header-bottom-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="mainmenu pull-left">
                            <ul class="nav navbar-nav collapse navbar-collapse">
                                <li><a href="~/Home/Index">Home</a></li>
                                <li><a href="~/Home/Contact">Contact</a></li>
                                <li><a href="~/Home/FAQ">FAQ</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-bottom-->
    </header><!--/header-->

@RenderBody()
    <footer id="footer">
        <!--footer-->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <p>Copyright &copy; 2017 Centriq cStore. All rights reserved</p>
                </div>
            </div>
        </div>
        <div id="adminLink" onclick="openNav()" class="button">
            <span class="vertical-text">ADMIN</span>
        </div>
        <div id="adminSideNav" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <a href="#">User Admin</a>
            <a href="#">Roles Admin</a>
            <a href="#">Manage Titles</a>
            <a href="#">Manage Authors</a>
            <hr/>
            <a href="@Url.Action("GetAuthors", "AuthorsADO")">AuthorsADO</a>
            <a href="@Url.Action("GetPublishers", "PublishersADO")">PublishersADO</a>

        </div>
        <div id="dialog" title="shopping cart">
            <p id="cart-contents">Your Cart is Currently Empty</p>
        </div>
    </footer><!--/footer-->

    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="~/Content/Scripts/cart.js"></script>
    <script type="text/javascript">
        function openNav() {
            document.getElementById('adminSideNav').style.width = "250px";
            document.getElementById('adminLink').style.display = "none";
        }
        function closeNav() {
            document.getElementById('adminSideNav').style.width = "0";
            document.getElementById('adminLink').style.display = "block";
        }
    </script>
    <script type="text/javascript">
        $(function () {
            $('#dialog').dialog({
                autoOpen: false, show: {
                    effect: "fade",
                    duration: 1000
                },
                hide: {
                    effect: "explode",
                    duration: 1000
                }
            });
            $('#cart-button').on('click', function () {
                $('#dialog').dialog('open');
            })
        });
    </script>
    @RenderSection("scripts", false)
</body>
</html>

cStoreMVC.UI/cStoreMVC.UI/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>